[Reference](https://medium.com/@Piotr_Szymanski/creating-a-python-function-to-calculate-returns-on-world-stock-market-indices-2d93c34d8d56)

In [7]:
pip install yfinance

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting yfinance
  Downloading yfinance-0.1.84-py2.py3-none-any.whl (29 kB)
Requirement already satisfied: numpy>=1.15 in /usr/local/lib/python3.7/dist-packages (from yfinance) (1.21.6)
Requirement already satisfied: lxml>=4.5.1 in /usr/local/lib/python3.7/dist-packages (from yfinance) (4.9.1)
Collecting requests>=2.26
  Downloading requests-2.28.1-py3-none-any.whl (62 kB)
     |████████████████████████████████| 62 kB 1.4 MB/s
Requirement already satisfied: appdirs>=1.4.4 in /usr/local/lib/python3.7/dist-packages (from yfinance) (1.4.4)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.7/dist-packages (from yfinance) (1.3.5)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.7/dist-packages (from yfinance) (0.0.11)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->yfinance) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->yfinance) (2022.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.24.0->yfinance) (1.15.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (1.24.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2.10)
Requirement already satisfied: charset-normalizer<3,>=2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2.1.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2022.9.24)
Installing collected packages: requests, yfinance
  Attempting uninstall: requests
    Found existing installation: requests 2.23.0
    Uninstalling requests-2.23.0:
      Successfully uninstalled requests-2.23.0
Successfully installed requests-2.28.1 yfinance-0.1.84

In [8]:
import yfinance as yf

In [9]:
# creating a list of stock indices 
tickers = ['^GSPC', '^DJI', '^IXIC','^RUT', '^FTSE', '^GDAXI', '^STOXX50E', '^FCHI', '^AXJO','^N225', '^HSI', '^NSEI', '000001.SS']
#initiating the function
def get_data(symbol, start):
    # downloading data, just the 'Close' column
    data = yf.download(tickers, start=start)['Close']
    # creating a dataframe with values from the close day
    frame = frame['Close'] = data.iloc[-1].to_frame()
    # getting values for each symbol from previous day
    frame['Previous Day'] = data.iloc[-2]
    # calculating the day-to-day return
    frame['% Change'] = ((frame['Close'] - frame["Previous Day"])/frame['Previous Day'])*100
    #resetting the index, the symbols are not index column anymore
    frame = frame.reset_index()
    #renaming the symbols column to 'Symbol'
    frame.rename(columns = {'index': "Symbol"}, inplace=True)
    #creating a list of names for stock indices
    index_names = ['Shanghai Composite', 'S&P/ASX 200', 'Dow Jones', 'CAC40', 'FTSE 100', 'DAX','S&P 500', 'Hang Seng', 'NASDAQ', 'Nikkei 225','Nifty 50', ' Russell 2000', ' EURO STOXX 50']
    #creating a column with stock names
    frame['Index Name'] = index_names
    #creating a column that indicates whether the index went up or down from previous day
    frame['Direction'] = frame['% Change'].apply(lambda x: 'Up' if x >= 0 else 'Down')
    #getting values from row 0 to calculate YTD return
    frame['Day 1 of Year'] = data.iloc[0].values
    #calculating YTD return
    frame['YTD %'] = ((frame['Close'] - frame["Day 1 of Year"])/frame['Day 1 of Year'])*100
    #creating a column that indicates whether the YTD is negative or positive
    frame['Overall YTD Return'] = frame['YTD %'].apply(lambda x: 'Positive' if x >= 0 else 'Negative')
    #dropping first column used to create 'frame' dataframe
    frame.drop(frame.columns[1], axis=1, inplace=True)
    #reorganizing the dataframe
    frame = frame[['Symbol', 'Index Name', 'Close','Previous Day', '% Change', 'Direction','YTD %', 'Overall YTD Return']]
    #closing the function
    return frame
#now the 'tickers' list can be plugged into the function 
data = get_data(tickers, "2022-01-04")

[*********************100%***********************]  13 of 13 completed

In [10]:
data

,Symbol,Index Name,Close,Previous Day,% Change,Direction,YTD %,Overall YTD Return
0,000001.SS,Shanghai Composite,2915.929932,2982.899902,-2.245130,Down,-19.722881,Negative
1,^AXJO,S&P/ASX 200,6785.700195,6845.100098,-0.867773,Down,-10.594477,Negative
2,^DJI,Dow Jones,32861.800781,32033.279297,2.586440,Up,-10.700775,Negative
3,^FCHI,CAC40,6273.049805,6244.029785,0.464764,Up,-14.272267,Negative
4,^FTSE,FTSE 100,7047.700195,7073.700195,-0.367559,Down,-6.095773,Negative
5,^GDAXI,DAX,13243.330078,13211.230469,0.242972,Up,-18.011208,Negative
6,^GSPC,S&P 500,3901.060059,3807.300049,2.462638,Up,-18.618390,Negative
7,^HSI,Hang Seng,14863.059570,15427.940430,-3.661415,Down,-36.182216,Negative
8,^IXIC,NASDAQ,11102.450195,10792.669922,2.870284,Up,-28.933948,Negative
9,^N225,Nikkei 225,27105.199219,27345.240234,-0.877816,Down,-7.496436,Negative
10,^NSEI,Nifty 50,17786.800781,17736.949219,0.281061,Up,-0.103617,Negative
11,^RUT,Russell 2000,1846.920044,1806.319946,2.247669,Up,-18.597366,Negative
12,^STOXX50E,EURO STOXX 50,3613.020020,3604.510010,0.236093,Up,-17.277146,Negative